steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [
            'build',
            '-t', 'gcr.io/$PROJECT_ID/kubekite:latest',
            '-t', 'gcr.io/$PROJECT_ID/kubekite:$COMMIT_SHA',
            '.'
        ]
images:
- 'gcr.io/$PROJECT_ID/kubekite:$COMMIT_SHA'
- 'gcr.io/$PROJECT_ID/kubekite:latest'