apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: kubekite
spec:
  selector: 
    matchLabels:
      application: kubekite
  replicas: 1
  template:
    metadata:
      labels:
        application: kubekite
    spec:
      serviceAccountName: kubekite
      containers:
      - name: kubekite
        image: your-registry/kubekite:%VERSION%
        imagePullPolicy: Always
        env:
          - name: BUILDKITE_API_TOKEN
            value: your-buildkite-token-here
          - name: BUILDKITE_ORG
            value: webflow
          - name: BUILDKITE_PIPELINE
            value: webflow-kubekite
        resources:
          requests:
            cpu: "0.2"
            memory: "50M"
          limits:
            memory: "100M"
            cpu: "0.4"
